name: CI/CD Projeto My Personal Daily

on:
  push:
    branches: [master]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Baixando Codigos Fontes do Projeto
              uses: actions/checkout@v3

            - name: Definindo Variaveis de Ambiente
              working-directory: ./
              run: |
                echo "TAG_VERSION=24071" >> .env

            - name: Setup JDK 17
              uses: actions/setup-java@v3
              with:
                distribuition: 'temurin'
                java-version: '17'
                cahce: maven

            - name: Build Projeto My Personal Daily
              working-directory: ./
              run: mvn package

            - name: Enviando Jar File para VPS
              uses: appleboy/ssh-action@master
              with:
                host: ${{ secrets.VPS_HOST }}
                username: ${{ secrets.VPS_USER }}
                key: ${{ secrets.SSH_VPS }}
                port: ${{ secrets.VPS_PORT }}
                script: |
                  scp ./target/${{ secrets.VM_JAR_FILE }} ${{ secrets.VPS_PATH_JAR_FILE}}