name: CI/CD Projeto My Personal Daily

on:
  push:
    branches: [master]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Baixando Codigos Fontes do Projeto
              uses: actions/checkout@v3

            - name: Definindo Variaveis de Ambiente
              working-directory: ./
              run: |
                echo "TAG_VERSION=24071" >> .env

            - name: Logando no Docker Hub
              uses: docker/login-action@v2.0.0
              with:
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Setup JDK 17
              uses: actions/setup-java@v3
              with:
                distribuition: 'temurin'
                java-version: '17'
                cahce: maven

            - name: Build Projeto My Personal Daily
              working-directory: ./
              run: mvn package

            - name: Gerando Imagem da aplicação
              working-directory: ./
              run: |
                docker build -t ${{ secrets.DOCKER_USERNAME }}/my-personal-daily:24071 .
                docker push ${{ secrets.DOCKER_USERNAME }}/my-personal-daily:24071